name: Docker Build and Deploy 

on:
  push: 
    branches: 
      - docker
  workflow_dispatch: 

jobs:
  #job 1
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-21
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Executar testes no container
        run: mvn -B verify
  #job 2
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: checkout cod
        uses: actions/checkout@v4

      - name: Login no dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push para Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/iec-t2-atividades:latest
          
      - name: Deploy no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}